### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by niftylettuce** [ValiMail/authentication-headers#13]
```sh
 File "/home/deploy/.local/lib/python3.6/site-packages/authheaders/__init__.py", line 291, in authenticate_message
   dmarc_result = check_dmarc(msg, spf_result, dkim_result, dnsfunc=dnsfunc, psddmarc=psddmarc)
 File "/home/deploy/.local/lib/python3.6/site-packages/authheaders/__init__.py", line 240, in check_dmarc
   from_domain = get_domain_part(from_header)
 File "/home/deploy/.local/lib/python3.6/site-packages/authheaders/__init__.py", line 51, in get_domain_part
   return res[0].decode('ascii')
IndexError: list index out of range
Error: Traceback (most recent call last):
 File "/var/www/production/source/node_modules/authheaders/scripts/authenticate-message.py", line 33, in <module>
   main()
 File "/var/www/production/source/node_modules/authheaders/scripts/authenticate-message.py", line 24, in main
   header = authheaders.authenticate_message(msg=message, authserv_id=authservId, ip=ip, mail_from=mailFrom, helo=helo, spf=True, dkim=True, arc=True)
 File "/home/deploy/.local/lib/python3.6/site-packages/authheaders/__init__.py", line 291, in authenticate_message
   dmarc_result = check_dmarc(msg, spf_result, dkim_result, dnsfunc=dnsfunc, psddmarc=psddmarc)
 File "/home/deploy/.local/lib/python3.6/site-packages/authheaders/__init__.py", line 240, in check_dmarc
   from_domain = get_domain_part(from_header)
 File "/home/deploy/.local/lib/python3.6/site-packages/authheaders/__init__.py", line 51, in get_domain_part
   return res[0].decode('ascii')
IndexError: list index out of range
```

**Comment by niftylettuce** [comment]
This must be a duplicate of #5, but oddly I am using their fork (with the apparent patch) and it's still not working.

**Comment by niftylettuce** [comment]
Fix is here: https://github.com/forwardemail/authentication-headers/commit/642dbb87e9ab3dfa02a300f61a810d768c8f0473

**Comment by niftylettuce** [comment]
The previous comment was a fix for something else.  I am still investigating how to fix this.

**Comment by niftylettuce** [comment]
I have fixed this in my fork per <https://github.com/forwardemail/authentication-headers/commit/4e9061a13b2bb02636331ddafaa25b762c3acd55>.

**Comment by niftylettuce** [comment]
The fix I did was actually NOT the fix, because now this error occurs:

```sh
20|smtp  | Error: Traceback (most recent call last):
20|smtp  |   File "/var/www/production/source/node_modules/authheaders/scripts/authenticate-message.py", line 36, in <module>
20|smtp  |     main()
20|smtp  |   File "/var/www/production/source/node_modules/authheaders/scripts/authenticate-message.py", line 25, in main
20|smtp  |     header = authheaders.authenticate_message(msg=message, authserv_id=authservId, ip=ip, mail_from=mailFrom, helo=helo, spf=True, dkim=True, arc=True)
20|smtp  |   File "/home/deploy/.local/lib/python3.6/site-packages/authheaders/__init__.py", line 298, in authenticate_message
20|smtp  |     return str(auth_res)
20|smtp  |   File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 476, in __str__
20|smtp  |     return ''.join((self.HEADER_FIELD_NAME, ': ', self.header_value()))
20|smtp  |   File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 492, in header_value
20|smtp  |     strs.append(str(result))
20|smtp  |   File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 222, in __str__
20|smtp  |     strs.append(str(property_))
20|smtp  |   File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 132, in __str__
20|smtp  |     return '%s.%s=%s' % (self.type, self.name, self.value.quote_if_needed())
20|smtp  | AttributeError: 'NoneType' object has no attribute 'quote_if_needed'
```

**Comment by msapiro** [comment]
I see the same issue, but in my case the From: domain contains uppercase and the issue is at https://github.com/ValiMail/authentication-headers/blob/master/authheaders/__init__.py#L48 where
```
    res = re.findall(b'@([a-z0-9.]+)', address)
```
should be
```
    res = re.findall(b'@([a-z0-9.]+)', address, re.IGNORECASE)
```
