### ISSUE TITLE
authres.core.SyntaxError: Syntax error: Expected method

### ISSUE THREAD

**Issue by niftylettuce** [ValiMail/authentication-headers#20]
I have discovered a core bug with this package.  Full stack trace below:

```sh
ARC signature error message: Traceback (most recent call last):
 File "/var/www/production/source/node_modules/dkimpy/scripts/arcsign.py", line 79, in <module>
   main()
 File "/var/www/production/source/node_modules/dkimpy/scripts/arcsign.py", line 70, in main
   srv_id, cv, linesep=dkim.util.get_linesep(message))
 File "/home/deploy/.local/lib/python3.6/site-packages/dkim/__init__.py", line 1399, in arc_sign
   timestamp=timestamp, standardize=standardize)
 File "/home/deploy/.local/lib/python3.6/site-packages/dkim/__init__.py", line 1025, in sign
   for res in ar_headers]
 File "/home/deploy/.local/lib/python3.6/site-packages/dkim/__init__.py", line 1025, in <listcomp>
   for res in ar_headers]
 File "/home/deploy/.local/lib/python3.6/site-packages/authres/__init__.py", line 206, in parse
   return authres.core.AuthenticationResultsHeader.parse(core_features(), string)
 File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 442, in parse
   return self.parse_value(feature_context, string)
 File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 454, in parse_value
   header._parse()
 File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 517, in _parse
   result = self._parse_resinfo()
 File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 550, in _parse_resinfo
   method, version, result = self._parse_methodspec()
 File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 570, in _parse_methodspec
   method, version = self._parse_method()
 File "/home/deploy/.local/lib/python3.6/site-packages/authres/core.py", line 583, in _parse_method
   raise SyntaxError('Expected method', self._parse_text)
```

**Comment by niftylettuce** [comment]
Sorry, this was filed under the wrong repo.

**Comment by niftylettuce** [comment]
Ref: https://bugs.launchpad.net/dkimpy/+bug/1891417
